"""create models

Revision ID: 09d6f4f24b5a
Revises: 6ebaa06f10e1
Create Date: 2026-03-10 21:40:57.191169

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '09d6f4f24b5a'
down_revision = '6ebaa06f10e1'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('applications', schema=None) as batch_op:
        batch_op.drop_column('message')

    with op.batch_alter_table('athletes', schema=None) as batch_op:
        batch_op.add_column(sa.Column('scout_id', sa.Integer(), nullable=True))
        batch_op.create_foreign_key(batch_op.f('fk_athletes_scout_id_scouts'), 'scouts', ['scout_id'], ['id'])

    with op.batch_alter_table('opportunities', schema=None) as batch_op:
        batch_op.add_column(sa.Column('club', sa.String(), nullable=True))
        batch_op.add_column(sa.Column('country', sa.String(), nullable=True))
        batch_op.drop_column('location')
        batch_op.drop_column('description')
        batch_op.drop_column('sport')

    with op.batch_alter_table('scouts', schema=None) as batch_op:
        batch_op.add_column(sa.Column('country', sa.String(), nullable=True))
        batch_op.alter_column('name',
               existing_type=sa.VARCHAR(),
               nullable=False)
        batch_op.drop_column('sport_focus')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('scouts', schema=None) as batch_op:
        batch_op.add_column(sa.Column('sport_focus', sa.VARCHAR(), nullable=True))
        batch_op.alter_column('name',
               existing_type=sa.VARCHAR(),
               nullable=True)
        batch_op.drop_column('country')

    with op.batch_alter_table('opportunities', schema=None) as batch_op:
        batch_op.add_column(sa.Column('sport', sa.VARCHAR(), nullable=True))
        batch_op.add_column(sa.Column('description', sa.VARCHAR(), nullable=True))
        batch_op.add_column(sa.Column('location', sa.VARCHAR(), nullable=True))
        batch_op.drop_column('country')
        batch_op.drop_column('club')

    with op.batch_alter_table('athletes', schema=None) as batch_op:
        batch_op.drop_constraint(batch_op.f('fk_athletes_scout_id_scouts'), type_='foreignkey')
        batch_op.drop_column('scout_id')

    with op.batch_alter_table('applications', schema=None) as batch_op:
        batch_op.add_column(sa.Column('message', sa.VARCHAR(), nullable=True))

    # ### end Alembic commands ###
