"""initial migration

Revision ID: bf484a3f78e1
Revises: 
Create Date: 2026-03-13 09:31:01.688905

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'bf484a3f78e1'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('scouts',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('organization', sa.String(), nullable=True),
    sa.Column('country', sa.String(), nullable=True),
    sa.Column('email', sa.String(), nullable=False),
    sa.Column('password', sa.String(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('email')
    )
    op.create_table('athletes',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('sport', sa.String(), nullable=True),
    sa.Column('country', sa.String(), nullable=True),
    sa.Column('age', sa.Integer(), nullable=True),
    sa.Column('email', sa.String(), nullable=False),
    sa.Column('password', sa.String(), nullable=True),
    sa.Column('scout_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['scout_id'], ['scouts.id'], name=op.f('fk_athletes_scout_id_scouts')),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('email')
    )
    op.create_table('opportunities',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('title', sa.String(), nullable=True),
    sa.Column('club', sa.String(), nullable=True),
    sa.Column('country', sa.String(), nullable=True),
    sa.Column('scout_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['scout_id'], ['scouts.id'], name=op.f('fk_opportunities_scout_id_scouts')),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('applications',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('status', sa.String(), nullable=True),
    sa.Column('athlete_id', sa.Integer(), nullable=True),
    sa.Column('opportunity_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['athlete_id'], ['athletes.id'], name=op.f('fk_applications_athlete_id_athletes')),
    sa.ForeignKeyConstraint(['opportunity_id'], ['opportunities.id'], name=op.f('fk_applications_opportunity_id_opportunities')),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('applications')
    op.drop_table('opportunities')
    op.drop_table('athletes')
    op.drop_table('scouts')
    # ### end Alembic commands ###
